In [2]:
import pandas as pd
import numpy as np

#### Q1. Pandas version

In [3]:
pd.__version__

'3.0.6'

#### Q2. Records count

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
len(df)

10000

#### Q3. Fuel types

In [73]:
df['fuel_type'].nunique()

3

#### Q4. Missing values

In [74]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

#### Q5. Max fuel efficiency

In [75]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [76]:
df['fuel_efficiency_mpg'][
    df['origin'] == 'Asia'
].max()

np.float64(41.2)

#### Q6. Valeur médiane de la puissance

In [77]:
df['horsepower'].median()

np.float64(254.0)

In [78]:
frequent_value = df['horsepower'].value_counts().idxmax()
frequent_value

np.float64(252.0)

In [79]:
horsepower = df['horsepower'].fillna(frequent_value)

In [80]:
horsepower.median()

np.float64(252.0)

#### Q7. Sum of weights

In [81]:
# 1. all the cars from Asia

df_asia_cars = df[
    df['origin'] == 'Asia'
]
df_asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [82]:
# 2 & 3. only columns vehicle_weight and model_year and the first 7 values

X_df = df_asia_cars[['vehicle_weight', 'model_year']].head(7)
X_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [83]:
# 4. the underlying NumPy array

X = X_df.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [84]:
# 5. the transpose of X
XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [89]:
# 5. multiplication between the transpose of X and X

XTX = XT.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [90]:
# 6. Invert XTX

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [108]:
# 7. New array
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [109]:
# 8
r = XTX_inv.dot(XT)
w = r.dot(y)
w

array([0.13644777, 0.2327492 ])

In [105]:
w.sum()

np.float64(0.36919696904925486)